# Numpy

In [1]:
import numpy as np

In [2]:
# print single dimensional array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
# print multi dimensional array
b = np.array([(1,2,3),(4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

## Numpy Operations

In [5]:
# dimension of an array
a = np.array([1,2,3])
a.ndim

1

In [6]:
b = np.array([(1,2,3),(4,5,6)])
b.ndim

2

In [7]:
# size of array (around 4 bytes)
b = np.array([(1,2,3),(4,5,6)])
b.itemsize

4

In [8]:
# datatype (integer 32 bit)
b = np.array([(1,2,3),(4,5,6)])
b.dtype

dtype('int32')

In [9]:
# shape (dim,no.of elements)
b = np.array([(1,2,3,4),(4,5,6,4)])
b.shape

(2, 4)

In [10]:
# reshaping - chnages the no. of rows and columns
b = np.array([(1,2,3),(4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b = np.array([(1,2,3),(4,5,6)])
b.reshape(3,2)  #(rows,cols)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
# picking an element from array
b = np.array([(1,2,3),(4,5,6)])
b[0]

array([1, 2, 3])

In [13]:
b = np.array([(1,2,3),(4,5,6)])
b[1]

array([4, 5, 6])

In [14]:
b = np.array([(1,2,3),(4,5,6)])
b[0,1]

2

In [15]:
b = np.array([(1,2,3),(4,5,6)])
b[1,0]

4

In [16]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])
b[0:,1]  # : represents all next rows

array([2, 5, 8])

In [17]:
c = np.array([(1,2),(4,5),(6,7),(8,9)])
c[0:3,1]

array([2, 5, 7])

In [18]:
# prints 10 values b/w 1 to 3
d = np.linspace(1,3,10)
d

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [19]:
e = np.array([1,2,4])
e.min()

1

In [20]:
e = np.array([(1,2,4),(4,5,6)])
e.max()

6

In [21]:
e = np.array([1,2,4])
e.sum()

7

In [22]:
f = np.array([(1,2,4),(3,5,6)])
f.max()

6

In [23]:
# rows are called axis=1
# cols are called axis=0
g = np.array([(1,2,4),(3,5,6)])
g

array([[1, 2, 4],
       [3, 5, 6]])

In [24]:
# returs sum of all cols values
g = np.array([(1,2,4),(3,5,6)])
g.sum(axis=0)

array([ 4,  7, 10])

In [25]:
# returs sum of all rows values
g = np.array([(1,2,4),(3,5,6)])
g.sum(axis=1)

array([ 7, 14])

In [26]:
# prints square root of each element
h = np.array([(1,2,4),(3,5,6)])
np.sqrt(h)

array([[1.        , 1.41421356, 2.        ],
       [1.73205081, 2.23606798, 2.44948974]])

In [27]:
# sum of array
i = np.array([(1,2,4),(3,5,6)])
j = np.array([(4,5,4),(3,4,1)])
i+j

array([[5, 7, 8],
       [6, 9, 7]])

In [28]:
i-j

array([[-3, -3,  0],
       [ 0,  1,  5]])

In [29]:
i*j

array([[ 4, 10, 16],
       [ 9, 20,  6]])

In [30]:
i/j

array([[0.25, 0.4 , 1.  ],
       [1.  , 1.25, 6.  ]])

In [31]:
# Concatination of arrays  -- 1. Vertical stacking 2. Horizontal Stacking

In [32]:
# 1. Vertical Stacking

i = np.array([(1,2,4),(3,5,6)])
j = np.array([(4,5,4),(3,4,1)])
np.vstack((i,j))

array([[1, 2, 4],
       [3, 5, 6],
       [4, 5, 4],
       [3, 4, 1]])

In [33]:
# 2. Horizontal Stacking

i = np.array([(1,2,4),(3,5,6)])
j = np.array([(4,5,4),(3,4,1)])
np.hstack((i,j))

array([[1, 2, 4, 4, 5, 4],
       [3, 5, 6, 3, 4, 1]])

In [35]:
np.arange(0,11,2)  # gves numbers betwwen 0 to 11 with step 2

array([ 0,  2,  4,  6,  8, 10])

In [37]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.ones((5,5))*255

array([[255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255.]])

In [42]:
np.random.randint(0,10)

8

In [44]:
np.random.randint(0,1000,(4,4))

array([[367, 771, 592,  16],
       [944, 809, 730, 527],
       [317, 322, 302, 860],
       [927, 150, 388, 828]])

In [82]:
np.random.seed(101)
arr =np.random.randint(0,100,12)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40,  4, 63])

In [83]:
arr.max()

95

In [84]:
arr.min()

4

In [85]:
arr.mean()

56.25

In [86]:
arr.argmax()  # index of maximum num

0

In [87]:
arr.argmin()  # index of minimum num

10

In [90]:
arr.reshape(3,4)   # must give dimension so that all values can come (row,column)

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63]])

In [91]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [92]:
mat[2,2]

22

In [97]:
mat[1,:] #row

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [94]:
mat[:,0] #col

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [96]:
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])